// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AzInfoApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiInfo
    {
        /// <summary>
        /// Initializes a new instance of the ApiInfo class.
        /// </summary>
        public ApiInfo() { }

        /// <summary>
        /// Initializes a new instance of the ApiInfo class.
        /// </summary>
        public ApiInfo(string verb = default(string), string apiVersion = default(string), string operation = default(string), string provider = default(string), string resourceType = default(string), string dataCenter = default(string), object operationDetails = default(object))
        {
            Verb = verb;
            ApiVersion = apiVersion;
            Operation = operation;
            Provider = provider;
            ResourceType = resourceType;
            DataCenter = dataCenter;
            OperationDetails = operationDetails;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verb")]
        public string Verb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apiVersion")]
        public string ApiVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operation")]
        public string Operation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provider")]
        public string Provider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceType")]
        public string ResourceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataCenter")]
        public string DataCenter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operationDetails")]
        public object OperationDetails { get; set; }

    }
}
